### ISSUE TITLE
Error with Unga-Bunga on first login

### ISSUE THREAD

**Issue by optix2000** [optix2000/totsugeki#52]
Error with Unga-Bunga when user registers online.

```
2021/09/05 00:38:39 http: panic serving 127.0.0.1:64380: runtime error: slice bounds out of range [:79] with capacity 64
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc000230e60)
        net/http/server.go:1804 +0x153
panic(0x10f3900, 0xc000394018)
        runtime/panic.go:971 +0x49a
github.com/optix2000/totsugeki/proxy.(*StatsGetPrediction).ParseLoginPrefix(0xc00022e0a0, 0xc00038e040, 0x3b, 0x40)
        github.com/optix2000/totsugeki/proxy/stats_get_prediction.go:136 +0x205
github.com/optix2000/totsugeki/proxy.(*StatsGetPrediction).StatsGetStateHandler.func1(0x21750187cb8, 0xc0000d0cc0, 0xc0000b8900)
        github.com/optix2000/totsugeki/proxy/stats_get_prediction.go:88 +0x317
net/http.HandlerFunc.ServeHTTP(0xc000252280, 0x21750187cb8, 0xc0000d0cc0, 0xc0000b8900)
        net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5/middleware.RequestLogger.func1.1(0x1197830, 0xc0000dcfc0, 0xc0000b8800)
        github.com/go-chi/chi/v5@v5.0.4/middleware/logger.go:57 +0x1de
net/http.HandlerFunc.ServeHTTP(0xc00021e870, 0x1197830, 0xc0000dcfc0, 0xc0000b8800)
        net/http/server.go:2049 +0x4b
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000216300, 0x1197830, 0xc0000dcfc0, 0xc0000b8700)
        github.com/go-chi/chi/v5@v5.0.4/mux.go:88 +0x330
net/http.serverHandler.ServeHTTP(0xc0002c2000, 0x1197830, 0xc0000dcfc0, 0xc0000b8700)
        net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc000230e60, 0x1198000, 0xc0000d0b00)
        net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        net/http/server.go:2993 +0x3b8
```

**Comment by optix2000** [comment]
Fixed in #62. Thanks @Borengar.
